GET http://127.0.0.1:5555/traveler/locations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMDk1MzM3MSwianRpIjoiNjUxZWRlMzUtODA1Yy00YjhmLTlhMDMtMjFiODg3ZDAyMzBhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6NCwibmJmIjoxNzIwOTUzMzcxLCJjc3JmIjoiYWNhNDVjM2ItZjMwZS00YjQ2LTkwMDktZWFiMGZiYmM3NmExIiwiZXhwIjoxNzIwOTU0MjcxfQ.WQHozm-msTozn1sEGcHr_OvJqzSutHc2iWf0nv9W9TY
Content-Type: application/json



